[package]
name = "rita"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>", "Ben <wangben3@gmail.com>"]
build = "build.rs"

[[bin]]
name = "rita_exit"
path = "src/exit.rs"

[[bin]]
name = "rita"
path = "src/client.rs"

[features]
default = []
system_alloc = []

[dependencies]
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types", features = ["actix"]}
babel_monitor = { path = "../babel_monitor" }
clu = { path = "../clu" }
exit_db = { path = "../exit_db" }
num256 = { path = "../num256" }
settings = { path = "../settings" }

actix = "0.5.8"
actix-web = { version = "0.6.13", default-features = false}
actix_derive = "0.2.0"
bytes = "0.4"
config = "0.8.0"
diesel = { version = "1.3.0", features = ["sqlite"] }
docopt = "0.8.3"
dotenv = "0.9.0"
env_logger = "^0.5.5"
eui48 = {git="https://github.com/althea-mesh/eui48.git"}
failure = "0.1.1"
futures = "0.1"
ip_network = "0.2"
lazy_static = "1.0"
log = "^0.4"
minihttpse = "0.1.6"
mockito = "0.9"
mockstream = { git = "https://github.com/lazy-bitfield/rust-mockstream.git" }
rand = "*"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
tokio-core = "0.1"
regex = "1.0"
trust-dns-resolver = "0.8"
