[package]
name = "althea_types"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
num256 = { path = "../num256" }
base64 = "0.9.0"
serde_derive = "1.0.24"
serde = "1.0.24"
serde_json = "1.0.8"
hex = "0.3.1"
eui48 = { git = "https://github.com/althea-mesh/eui48", features = ["serde"] }
actix = {git="https://github.com/kingoflolz/actix", branch="mocking", optional=true}